language: scala
scala:
  - 2.11.7
  - 2.10.6
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
